version: '3.1'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mck-discord-logs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./config.json:/app/config.json